version: "3.9"

services:

    web:
        build: .
        container_name: web
        restart: unless-stopped
        env_file:
          - .ENV
        ports:
            - 8000:8000
        command: python main.py

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379